### PR TITLE
edit readme

### PR DESCRIPTION
**Pull request by miaiseman**
I tried to add a line at the end about evaluation, since that's part of CRISP-DM. But it's pretty minor.  Otherwise, this is supposed to basically mimic the blog post, which I think is fine. Let me know if you find anything off!

### CODE REVIEW

**Comment by werlindo** [comment]
Live editing! these are prolly going to be super minor:

- A line above `Bernie Sanders?…`

- `Through the Reddit API, and a little help from this article` -> link Alex’s blog?

-  Didn’t suggest before, but maybe change:
`an Amazon Web Services Relational Database Service.`
to:
`a PostgreSQL database on AWS Relational Database Services.`

That’s it!
Thanks!

**Comment by miaiseman** [comment]
Okay- can you take a look now? How's that look?

**Comment by werlindo** [comment]
I'm good with this!

**Review by werlindo — COMMENTED** [review]
Perf

**Pull request merged**
